library(shiny)
library(plotly)
#library(devtools)
#install_github('tinnaing347/bRema')
#library(bRema)


ui <- fluidPage(
	headerPanel('Outlier Analysis'),
	sidebarPanel(
		fileInput("file2", "Choose Utility CSV File", accept = c("text/csv","text/comma-separated-values,text/plain", ".csv")),
    	fileInput("file1", "Choose Best Model CSV/All Model CSV File", accept = c("text/csv","text/comma-separated-values,text/plain", ".csv")),
    	fileInput("file7", "Choose Building Info CSV File", accept = c("text/csv","text/comma-separated-values,text/plain", ".csv")),
        fileInput("file9", "Choose Prev Year Utility CSV File", accept = c("text/csv","text/comma-separated-values,text/plain", ".csv")),
    	uiOutput("first"),
        fluidRow(
            column(4, actionButton(inputId = "prevBin", label = "Previous")),
            column(4, actionButton(inputId = "nextBin", label = "Next"))
        #column(2, checkboxInput(inputId = 'aggregate', label = "Aggregate", value = FALSE, width = NULL))
    )
	),
	mainPanel(
		tabsetPanel(
			tabPanel('Elec',
				br(),
                h3("Parameter Model from BEMA"),
				plotlyOutput('plot2'),
            	br(),
            	actionButton(inputId = "graph_elec", label = "Run"),
            	verbatimTextOutput("outlier_elec"),
            	br(),
            	tableOutput('params_df'),
            	br(),
            	tableOutput('stat_df'),
            	br(),
                h3("Parameter Model using user's outlier"),
            	plotlyOutput('plot_out'),
                br(),
                tableOutput('params_df_out'),
                br(),
                tableOutput('stat_df_out'),
                br(),
                h3("Parameter Model using outlier calculated by Mahalanobis Distance"),
                plotlyOutput('m_plot'),
                br(),
                tableOutput('m_param'),
                br(),
                tableOutput('m_stat'),
                br(),
                h3("Parameter Model using outlier calculated by Ellipse Confidence Interval"),
                plotlyOutput('e_plot'),
                br(),
                tableOutput('e_param'),
                br(),
                tableOutput('e_stat'),
                br(),
                h3("Parameter Model using estimated Previous Year Data"),
                plotlyOutput('p_e_plot'),
                br(),
                tableOutput('p_e_param'),
                br(),
                tableOutput('p_e_stat'),
                h3("Parameter Model using estimated aggregate Data"),
                plotlyOutput('a_e_plot'),
                br(),
                tableOutput('a_e_param'),
                br(),
                tableOutput('a_e_stat')
			),
			tabPanel('Fuel',
				br(),
                h3("Parameter Model from BEMA"),
				plotlyOutput('plot22'),
            	br(),
                actionButton(inputId = "graph_fuel", label = "Run"),
                verbatimTextOutput("outlier_fuel"),
                br(),
            	tableOutput('params_df2'),
            	br(),
            	tableOutput('stat_df2'),
            	br(),
                h3("Parameter Model using user's outlier"),
                plotlyOutput('plot_out2'),
                br(),
                tableOutput('params_df_out2'),
                br(),
                tableOutput('stat_df_out2'),
                br(),
                h3("Parameter Model using outlier calculated by Mahalanobis Distance"),
                plotlyOutput('m_plot2'),
                br(),
                tableOutput('m_param2'),
                br(),
                tableOutput('m_stat2'),
                br(),
                h3("Parameter Model using outlier calculated by Ellipse Confidence Interval"),
                plotlyOutput('e_plot2'),
                br(),
                tableOutput('e_param2'),
                br(),
                tableOutput('e_stat2'),
                br(),
                h3("Parameter Model using estimated Previous Year Data"),
                plotlyOutput('p_f_plot'),
                br(),
                tableOutput('p_f_param'),
                br(),
                tableOutput('p_f_stat'),
                br(),
                h3("Parameter Model using estimated aggregate Data"),
                plotlyOutput('a_f_plot'),
                br(),
                tableOutput('a_f_param'),
                br(),
                tableOutput('a_f_stat')
			),
            tabPanel('Stats',
                br(),
                h3("Elec Output"),
                tableOutput('elec_param_combined'),
                br(),
                h3("Fuel Output"),
                tableOutput('fuel_param_combined')
            )
		)
	)
)